version: "3"
services:
  app:
    container_name: bp_api_app
    build:
      context: ../
      dockerfile: .docker/Dockerfile.app
    environment:
      # コンテナ内で利用する環境変数
      # 注意として、ここに指定してる変数は、Dockerfileには共有されない。
      ENV: dev
      PYTHONPATH: ./
      PYTHONDONTWRITEBYTECODE: 1
      SQLALCHEMY_ENGINE_URI: mysql+pymysql://hogehoge:hogehoge@bp_api_db:3306/hogedb
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
  db:
    container_name: bp_api_db
    image: mysql:8.0
    environment:
      MYSQL_USER: hogehoge
      MYSQL_PASSWORD: hogehoge
      MYSQL_DATABASE: hogedb
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_ROOT_HOST: "%"
      TZ: "Asia/Tokyo"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
      - ./logs/mysql:/var/log/mysql
    networks:
      - backend
  web:
    container_name: web
    image: nginx
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    networks:
      - backend
networks:
  backend:
    driver: bridge
